/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.time.LocalDate;
import java.time.MonthDay;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

public class AplikasiPenghitungUmur extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenghitungUmur
     */
    
    
    public AplikasiPenghitungUmur() {
        initComponents();


       
        
        
        // Deteksi perubahan tanggal otomatis
        dateChooserTanggalLahir.addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) {
                txtUmur.setText("");
            }
        });
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTanggal = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        dateChooserTanggalLahir = new com.toedter.calendar.JDateChooser();
        btnHitung = new javax.swing.JButton();
        txtUmur = new javax.swing.JTextField();
        lblUlangTahunBerikutnya = new javax.swing.JLabel();
        txtUlangTahunBerikutnya = new javax.swing.JTextField();
        lblAcaraSpesial = new javax.swing.JLabel();
        txtAcaraSpesial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTanggal.setText("Pilih tanggal lahir :");

        lblHasil.setText("Umur anda :");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        txtUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmurActionPerformed(evt);
            }
        });

        lblUlangTahunBerikutnya.setText("Ulang Tahun Berikutnya :");

        txtUlangTahunBerikutnya.setText(" ");

        lblAcaraSpesial.setText("Acara Spesial :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAcaraSpesial)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHasil)
                            .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUlangTahunBerikutnya, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUlangTahunBerikutnya, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTanggal)
                        .addGap(33, 33, 33)
                        .addComponent(dateChooserTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnHitung))
                    .addComponent(txtAcaraSpesial))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTanggal)
                    .addComponent(dateChooserTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHasil)
                    .addComponent(lblUlangTahunBerikutnya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUlangTahunBerikutnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcaraSpesial)
                .addGap(18, 18, 18)
                .addComponent(txtAcaraSpesial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        Date tanggalLahir = dateChooserTanggalLahir.getDate();
        if (tanggalLahir == null) {
            JOptionPane.showMessageDialog(this, "Silakan pilih tanggal lahir terlebih dahulu!");
            return;
        }

        LocalDate lahir = tanggalLahir.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate sekarang = LocalDate.now();
        Period selisih = Period.between(lahir, sekarang);

        txtUmur.setText(String.format("%d tahun, %d bulan, %d hari",
            selisih.getYears(), selisih.getMonths(), selisih.getDays()));

        // Hitung ulang tahun berikutnya
        LocalDate ulangTahunBerikutnya = lahir.withYear(sekarang.getYear());
        if (!ulangTahunBerikutnya.isAfter(sekarang)) {
            ulangTahunBerikutnya = ulangTahunBerikutnya.plusYears(1);
        }

        Period menujuUlangTahun = Period.between(sekarang, ulangTahunBerikutnya);
        txtUlangTahunBerikutnya.setText(String.format("%s (dalam %d bulan %d hari lagi)",
            ulangTahunBerikutnya.toString(), menujuUlangTahun.getMonths(), menujuUlangTahun.getDays()));

        // --- Panggil API hari libur untuk bulan & tahun ulangTahunBerikutnya ---
        try {
            int queryMonth = ulangTahunBerikutnya.getMonthValue();
            int queryYear = ulangTahunBerikutnya.getYear();

            // contoh API publik: https://api-harilibur.vercel.app/api?month=8&year=2020
            String apiUrl = String.format("https://calendarific.com/api/v2/holidays?api_key=YOUR_API_KEY&country=ID&year=%d&month=%d", queryMonth, queryYear);

            JSONArray holidays = fetchJsonArrayFromUrl(apiUrl);

            // Periksa apakah salah satu holiday berisi tanggal yang sama`
            String found = null;
            String targetDate = ulangTahunBerikutnya.toString(); // "YYYY-MM-DD"
            if (holidays != null) {
                for (int i = 0; i < holidays.length(); i++) {
                    JSONObject h = holidays.getJSONObject(i);
                    // Struktur JSON bisa berbeda tergantung API: cari properti "date" atau "holiday_date" / "tanggal"
                    String dateStr = null;
                    if (h.has("date")) dateStr = h.optString("date", null);
                    else if (h.has("tanggal")) dateStr = h.optString("tanggal", null);
                    else if (h.has("holiday_date")) dateStr = h.optString("holiday_date", null);
                    else if (h.has("holiday")) {
                        // holiday bisa berupa objek
                        Object holidayObj = h.get("holiday");
                        if (holidayObj instanceof JSONObject) {
                            JSONObject ho = (JSONObject) holidayObj;
                            if (ho.has("date")) dateStr = ho.optString("date", null);
                        }
                    }

                    // nama acara
                    String name = null;
                    if (h.has("name")) name = h.optString("name", null);
                    else if (h.has("libur")) name = h.optString("libur", null);
                    else if (h.has("keterangan")) name = h.optString("keterangan", null);
                    else if (h.has("holiday")) {
                        Object holidayObj = h.get("holiday");
                        if (holidayObj instanceof JSONObject) {
                            JSONObject ho = (JSONObject) holidayObj;
                            if (ho.has("name")) name = ho.optString("name", null);
                        }
                    }

                    if (dateStr != null && dateStr.startsWith(targetDate)) {
                        found = (name != null ? name : "Libur / acara khusus");
                        break;
                    }
                    // beberapa API menyimpan tanggal dalam format "dd-mm-yyyy", jadi cek juga kemungkinan itu
                    if (dateStr != null && dateStr.contains("-")) {
                        // try dd-mm-yyyy
                        String[] parts = dateStr.split("-");
                        if (parts.length == 3) {
                            String alt = String.format("%s-%s-%s", parts[2], parts[1], parts[0]);
                            if (alt.equals(targetDate)) {
                                found = (name != null ? name : "Libur / acara khusus");
                                break;
                            }
                        }
                    }
                }
            }

            if (found != null) {
                txtAcaraSpesial.setText(found + " (Libur Nasional)");
            } else {
                // kalau tidak ditemukan dari API, fallback ke check manual sederhana (MonthDay)
                MonthDay md = MonthDay.from(ulangTahunBerikutnya);
                // contoh manual: cek 1 Jan, 17 Aug, 25 Dec
                if (md.equals(MonthDay.of(1,1))) txtAcaraSpesial.setText("Tahun Baru Masehi");
                else if (md.equals(MonthDay.of(8,17))) txtAcaraSpesial.setText("Hari Kemerdekaan RI");
                else if (md.equals(MonthDay.of(12,25))) txtAcaraSpesial.setText("Hari Natal");
                else txtAcaraSpesial.setText("Tidak ada acara spesial terdaftar pada hari itu.");
            }

        } catch (Exception ex) {
            // Kalau gagal memanggil API (no internet / error), beri pesan informatif dan jangan crash
            txtAcaraSpesial.setText("Gagal ambil data hari libur (cek koneksi).");
            System.err.println("Error saat memanggil API hari libur: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmurActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUmurActionPerformed

        private JSONArray fetchJsonArrayFromUrl(String urlStr) throws Exception {
        URL url = new URL(urlStr);
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("GET");
        con.setConnectTimeout(5000);
        con.setReadTimeout(7000);
        con.setRequestProperty("Accept", "application/json");

        int status = con.getResponseCode();
        BufferedReader in;
        if (status >= 200 && status < 300) {
            in = new BufferedReader(new InputStreamReader(con.getInputStream(), "UTF-8"));
        } else {
            in = new BufferedReader(new InputStreamReader(con.getErrorStream(), "UTF-8"));
        }

        StringBuilder content = new StringBuilder();
        String line;
        while ((line = in.readLine()) != null) {
            content.append(line);
        }
        in.close();
        con.disconnect();

        // parsing: beberapa API mengembalikan object { data: [...] } atau langsung array [...]
        String raw = content.toString().trim();
        if (raw.isEmpty()) return null;

        if (raw.startsWith("[")) {
            return new JSONArray(raw);
        } else if (raw.startsWith("{")) {
            JSONObject obj = new JSONObject(raw);
            // coba beberapa kemungkinan key yang berisi array
            if (obj.has("data") && obj.get("data") instanceof JSONArray) {
                return obj.getJSONArray("data");
            } else if (obj.has("holidays") && obj.get("holidays") instanceof JSONArray) {
                return obj.getJSONArray("holidays");
            } else if (obj.has("result") && obj.get("result") instanceof JSONArray) {
                return obj.getJSONArray("result");
            } else {
                // Jika isi object tapi tidak ketemu array, kembalikan array kosong
                return new JSONArray();
            }
        } else {
            return new JSONArray();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungUmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungUmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungUmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungUmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenghitungUmur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private com.toedter.calendar.JDateChooser dateChooserTanggalLahir;
    private javax.swing.JLabel lblAcaraSpesial;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblUlangTahunBerikutnya;
    private javax.swing.JTextField txtAcaraSpesial;
    private javax.swing.JTextField txtUlangTahunBerikutnya;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
